# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Interface/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(679, 610)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelWelcome = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.labelWelcome.setFont(font)
        self.labelWelcome.setObjectName("labelWelcome")
        self.verticalLayout_2.addWidget(self.labelWelcome, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.subdomainButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.subdomainButton.setFont(font)
        self.subdomainButton.setObjectName("subdomainButton")
        self.verticalLayout.addWidget(self.subdomainButton)
        self.dnsButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.dnsButton.setFont(font)
        self.dnsButton.setObjectName("dnsButton")
        self.verticalLayout.addWidget(self.dnsButton)
        self.CertificateButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.CertificateButton.setFont(font)
        self.CertificateButton.setObjectName("CertificateButton")
        self.verticalLayout.addWidget(self.CertificateButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout_2.addWidget(self.calendarWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelWelcome.setText(_translate("MainWindow", "You are welcome"))
        self.subdomainButton.setText(_translate("MainWindow", "Subdomain scan"))
        self.dnsButton.setText(_translate("MainWindow", "Dns scan"))
        self.CertificateButton.setText(_translate("MainWindow", "Certificate scan"))
