# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Interface/subdomain_Scanner.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1412, 784)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        Dialog.setFont(font)
        self.labelEnterDomain = QtWidgets.QLabel(Dialog)
        self.labelEnterDomain.setGeometry(QtCore.QRect(610, 0, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.labelEnterDomain.setFont(font)
        self.labelEnterDomain.setStyleSheet("color: black; \n"
"font-weight: bold; \n"
"font-size: 12px;\n"
"")
        self.labelEnterDomain.setObjectName("labelEnterDomain")
        self.plainTextEditLogs = QtWidgets.QTextBrowser(Dialog)
        self.plainTextEditLogs.setGeometry(QtCore.QRect(0, 70, 431, 711))
        self.plainTextEditLogs.setStyleSheet("background-color: #f5f5f5; \n"
"color: black; \n"
"border: 1px solid gray;\n"
"")
        self.plainTextEditLogs.setObjectName("plainTextEditLogs")
        self.labelScanningLogs = QtWidgets.QLabel(Dialog)
        self.labelScanningLogs.setGeometry(QtCore.QRect(0, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.labelScanningLogs.setFont(font)
        self.labelScanningLogs.setStyleSheet("color: black; \n"
"font-weight: bold; \n"
"font-size: 12px;\n"
"")
        self.labelScanningLogs.setObjectName("labelScanningLogs")
        self.progressBarScan = QtWidgets.QProgressBar(Dialog)
        self.progressBarScan.setGeometry(QtCore.QRect(0, 50, 431, 21))
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.progressBarScan.setFont(font)
        self.progressBarScan.setStyleSheet("background-color: lightgray; \n"
"color: darkgreen; \n"
"border-radius: 5px;\n"
"")
        self.progressBarScan.setProperty("value", 0)
        self.progressBarScan.setObjectName("progressBarScan")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(429, 510, 541, 271))
        self.tabWidget.setStyleSheet("QTabBar::tab { \n"
"    background-color: lightblue; \n"
"    color: black; \n"
"    font-weight: bold; \n"
"    border: 1px solid gray; \n"
"    padding: 5px; \n"
"}\n"
"QTabBar::tab:selected { \n"
"    background-color: #add8e6; \n"
"    color: darkblue; \n"
"}\n"
"")
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_request = QtWidgets.QWidget()
        self.tab_request.setStyleSheet("QWidget {\n"
"    background-color: #f0f8ff;  /* Светло-голубой фон */\n"
"    border: 1px solid lightblue;  /* Синяя рамка */\n"
"}\n"
"QGroupBox {\n"
"    color: darkblue;  /* Синий текст заголовка */\n"
"    font-weight: bold;\n"
"    border: 1px solid lightblue;  /* Синяя рамка группы */\n"
"    background-color: #f9f9f9;  /* Светло-серый фон внутри группы */\n"
"}\n"
"QLabel {\n"
"    color: darkblue;  /* Синий текст */\n"
"    font-weight: bold;\n"
"}\n"
"QLineEdit {\n"
"    background-color: white;  /* Белый фон */\n"
"    color: black;  /* Чёрный текст */\n"
"    border: 1px solid gray;  /* Серая рамка */\n"
"}\n"
"QPushButton {\n"
"    background-color: lightgray;  /* Светло-серый фон */\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    border: 1px solid gray;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: lightblue;  /* Светло-голубой при наведении */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #87ceeb;  /* Голубой при нажатии */\n"
"}\n"
"")
        self.tab_request.setObjectName("tab_request")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_request)
        self.verticalLayout_2.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBoxRequests = QtWidgets.QGroupBox(self.tab_request)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxRequests.setFont(font)
        self.groupBoxRequests.setStyleSheet("")
        self.groupBoxRequests.setTitle("")
        self.groupBoxRequests.setObjectName("groupBoxRequests")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxRequests)
        self.gridLayout.setObjectName("gridLayout")
        self.labelMaxReq = QtWidgets.QLabel(self.groupBoxRequests)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelMaxReq.setFont(font)
        self.labelMaxReq.setObjectName("labelMaxReq")
        self.gridLayout.addWidget(self.labelMaxReq, 3, 0, 1, 1)
        self.lineEditInterval = QtWidgets.QLineEdit(self.groupBoxRequests)
        self.lineEditInterval.setObjectName("lineEditInterval")
        self.gridLayout.addWidget(self.lineEditInterval, 4, 1, 1, 1)
        self.labelTimeOutReq = QtWidgets.QLabel(self.groupBoxRequests)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelTimeOutReq.setFont(font)
        self.labelTimeOutReq.setObjectName("labelTimeOutReq")
        self.gridLayout.addWidget(self.labelTimeOutReq, 0, 1, 1, 1)
        self.lineEditTimeout = QtWidgets.QLineEdit(self.groupBoxRequests)
        self.lineEditTimeout.setObjectName("lineEditTimeout")
        self.gridLayout.addWidget(self.lineEditTimeout, 1, 1, 1, 1)
        self.labelIntervalReq = QtWidgets.QLabel(self.groupBoxRequests)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelIntervalReq.setFont(font)
        self.labelIntervalReq.setObjectName("labelIntervalReq")
        self.gridLayout.addWidget(self.labelIntervalReq, 3, 1, 1, 1)
        self.lineEditRequestCount = QtWidgets.QLineEdit(self.groupBoxRequests)
        self.lineEditRequestCount.setObjectName("lineEditRequestCount")
        self.gridLayout.addWidget(self.lineEditRequestCount, 1, 0, 1, 1)
        self.lineEditRequestLimit = QtWidgets.QLineEdit(self.groupBoxRequests)
        self.lineEditRequestLimit.setObjectName("lineEditRequestLimit")
        self.gridLayout.addWidget(self.lineEditRequestLimit, 4, 0, 1, 1)
        self.labelReqCount = QtWidgets.QLabel(self.groupBoxRequests)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelReqCount.setFont(font)
        self.labelReqCount.setObjectName("labelReqCount")
        self.gridLayout.addWidget(self.labelReqCount, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBoxRequests)
        self.tabWidget.addTab(self.tab_request, "")
        self.tab_attack = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_attack.sizePolicy().hasHeightForWidth())
        self.tab_attack.setSizePolicy(sizePolicy)
        self.tab_attack.setObjectName("tab_attack")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_attack)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBoxAttackMode = QtWidgets.QGroupBox(self.tab_attack)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxAttackMode.setFont(font)
        self.groupBoxAttackMode.setStyleSheet("QWidget {\n"
"    background-color: #e6f7ff;  /* Светло-голубой фон */\n"
"    border: 1px solid gray;  /* Серая рамка */\n"
"}\n"
"QGroupBox {\n"
"    color: darkgreen;  /* Тёмно-зелёный текст */\n"
"    font-weight: bold;\n"
"    border: 1px solid lightgreen;  /* Светло-зелёная рамка */\n"
"    background-color: #f4fff9;  /* Светло-зелёный фон */\n"
"}\n"
"QLabel {\n"
"    color: darkgreen;  /* Тёмно-зелёный текст */\n"
"    font-weight: bold;\n"
"}\n"
"QCheckBox {\n"
"    color: black;  /* Чёрный текст */\n"
"    font-weight: bold;\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 15px; \n"
"    height: 15px;\n"
"}\n"
"QPushButton {\n"
"    background-color: lightgray;  /* Светло-серый фон */\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    border: 1px solid gray;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #ccffcc;  /* Светло-зелёный при наведении */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #99ff99;  /* Зелёный при нажатии */\n"
"}\n"
"")
        self.groupBoxAttackMode.setTitle("")
        self.groupBoxAttackMode.setObjectName("groupBoxAttackMode")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBoxAttackMode)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBoxSneakyAttack = QtWidgets.QCheckBox(self.groupBoxAttackMode)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxSneakyAttack.setFont(font)
        self.checkBoxSneakyAttack.setObjectName("checkBoxSneakyAttack")
        self.verticalLayout_3.addWidget(self.checkBoxSneakyAttack)
        self.checkBoxModerateAttack = QtWidgets.QCheckBox(self.groupBoxAttackMode)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxModerateAttack.setFont(font)
        self.checkBoxModerateAttack.setObjectName("checkBoxModerateAttack")
        self.verticalLayout_3.addWidget(self.checkBoxModerateAttack)
        self.checkBoxAggressiveAttack = QtWidgets.QCheckBox(self.groupBoxAttackMode)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxAggressiveAttack.setFont(font)
        self.checkBoxAggressiveAttack.setObjectName("checkBoxAggressiveAttack")
        self.verticalLayout_3.addWidget(self.checkBoxAggressiveAttack)
        self.verticalLayout.addWidget(self.groupBoxAttackMode)
        self.checkBoxShowRequests = QtWidgets.QCheckBox(self.tab_attack)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxShowRequests.setFont(font)
        self.checkBoxShowRequests.setStyleSheet("QCheckBox {\n"
"    color: darkgreen;  /* Тёмно-зелёный текст */\n"
"    font-weight: bold;  /* Полужирный шрифт */\n"
"    spacing: 5px;  /* Расстояние между текстом и флажком */\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;  /* Ширина флажка */\n"
"    height: 15px;  /* Высота флажка */\n"
"    background-color: lightgreen;  /* Светло-зелёный фон */\n"
"    border: 1px solid darkgreen;  /* Тёмно-зелёная рамка */\n"
"    border-radius: 3px;  /* Скруглённые края */\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #99ff99;  /* Зелёный фон при включении */\n"
"    border: 1px solid darkgreen;  /* Тёмно-зелёная рамка */\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;  /* Белый фон при выключении */\n"
"    border: 1px solid gray;  /* Серая рамка */\n"
"}\n"
"")
        self.checkBoxShowRequests.setObjectName("checkBoxShowRequests")
        self.verticalLayout.addWidget(self.checkBoxShowRequests)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab_attack, "")
        self.tab_output = QtWidgets.QWidget()
        self.tab_output.setStyleSheet("QWidget {\n"
"    background-color: lightblue;  /* Светло-серый фон */\n"
"    border: 1px solid gray;    /* Тонкая серая рамка */\n"
"}\n"
"QLabel {\n"
"    color: darkblue;           /* Синий текст для заголовков */\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton {\n"
"    background-color: lightgray;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    border: 1px solid gray;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: green;  /* Светло-голубой при наведении */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #87ceeb;  /* Голубой при нажатии */\n"
"}\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid gray;\n"
"}\n"
"")
        self.tab_output.setObjectName("tab_output")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_output)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.comboBoxFormat = QtWidgets.QComboBox(self.tab_output)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBoxFormat.setFont(font)
        self.comboBoxFormat.setStyleSheet("QComboBox {\n"
"    background-color: white;  /* Белый фон */\n"
"    color: black;  /* Чёрный текст */\n"
"    border: 1px solid gray;  /* Серая рамка */\n"
"    border-radius: 5px;  /* Скруглённые углы */\n"
"    padding: 2px;  /* Внутренний отступ */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border-left: 1px solid gray;  /* Вертикальная линия для выпадающего списка */\n"
"    background-color: lightgray;  /* Светло-серый фон кнопки */\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(down_arrow_icon.png);  /* Укажите путь к иконке стрелки, если нужно */\n"
"    width: 10px; \n"
"    height: 10px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #f9f9f9;  /* Светло-серый фон для выпадающего списка */\n"
"    color: black;  /* Чёрный текст */\n"
"    border: 1px solid gray;  /* Серая рамка */\n"
"    selection-background-color: #add8e6;  /* Голубой фон для выбранного элемента */\n"
"    selection-color: white;  /* Белый текст для выбранного элемента */\n"
"}\n"
"")
        self.comboBoxFormat.setObjectName("comboBoxFormat")
        self.comboBoxFormat.addItem("")
        self.comboBoxFormat.addItem("")
        self.comboBoxFormat.addItem("")
        self.verticalLayout_5.addWidget(self.comboBoxFormat)
        self.labelEnterFile = QtWidgets.QLabel(self.tab_output)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.labelEnterFile.setFont(font)
        self.labelEnterFile.setObjectName("labelEnterFile")
        self.verticalLayout_5.addWidget(self.labelEnterFile, 0, QtCore.Qt.AlignHCenter)
        self.lineEditFileName = QtWidgets.QLineEdit(self.tab_output)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(15)
        self.lineEditFileName.setFont(font)
        self.lineEditFileName.setObjectName("lineEditFileName")
        self.verticalLayout_5.addWidget(self.lineEditFileName)
        self.pushButtonSaveFormat = QtWidgets.QPushButton(self.tab_output)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSaveFormat.setFont(font)
        self.pushButtonSaveFormat.setObjectName("pushButtonSaveFormat")
        self.verticalLayout_5.addWidget(self.pushButtonSaveFormat)
        self.tabWidget.addTab(self.tab_output, "")
        self.tab_treeWidget = QtWidgets.QWidget()
        self.tab_treeWidget.setStyleSheet("QWidget {\n"
"    background-color: #eef7fa;  /* Светло-голубой фон */\n"
"    border: 1px solid lightblue;\n"
"}\n"
"QPushButton {\n"
"    background-color: lightgray;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    border: 1px solid gray;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: lightblue;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #87ceeb;\n"
"}\n"
"QTreeWidget {\n"
"    background-color: #f9f9f9;\n"
"    alternate-background-color: #e9f7fc;  /* Чередующиеся строки */\n"
"    border: 1px solid gray;\n"
"}\n"
"QTreeWidget::item {\n"
"    color: black;\n"
"}\n"
"QTreeWidget::item:selected {\n"
"    background-color: #add8e6;\n"
"    color: white;\n"
"}\n"
"")
        self.tab_treeWidget.setObjectName("tab_treeWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_treeWidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButtonExportJson = QtWidgets.QPushButton(self.tab_treeWidget)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonExportJson.setFont(font)
        self.pushButtonExportJson.setObjectName("pushButtonExportJson")
        self.verticalLayout_7.addWidget(self.pushButtonExportJson)
        self.tabWidget.addTab(self.tab_treeWidget, "")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(430, 50, 541, 271))
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("color: darkblue; \n"
"font-weight: bold; \n"
"font-size: 19px;\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.labelExample = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.labelExample.setFont(font)
        self.labelExample.setStyleSheet("color: black; \n"
"font-weight: bold; \n"
"font-size: 18px;\n"
"")
        self.labelExample.setObjectName("labelExample")
        self.verticalLayout_6.addWidget(self.labelExample)
        self.lineEditDomain = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditDomain.setFont(font)
        self.lineEditDomain.setStyleSheet("QLineEdit {\n"
"    background-color: white; \n"
"    color: black; \n"
"    border: 1px solid gray;\n"
"}\n"
"")
        self.lineEditDomain.setObjectName("lineEditDomain")
        self.verticalLayout_6.addWidget(self.lineEditDomain)
        self.pushButtonScan = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonScan.setFont(font)
        self.pushButtonScan.setStyleSheet("QPushButton { \n"
"    background-color: lightgray; \n"
"    color: black; \n"
"    font-weight: bold; \n"
"    border: 1px solid gray; \n"
"    border-radius: 5px; \n"
"}\n"
"QPushButton:hover { \n"
"    background-color: green; \n"
"}\n"
"QPushButton:pressed { \n"
"    background-color: #87ceeb; \n"
"}\n"
"")
        self.pushButtonScan.setObjectName("pushButtonScan")
        self.verticalLayout_6.addWidget(self.pushButtonScan)
        self.pushButtonClearLogs = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonClearLogs.setFont(font)
        self.pushButtonClearLogs.setStyleSheet("QPushButton { \n"
"    background-color: lightgray; \n"
"    color: black; \n"
"    font-weight: bold; \n"
"    border: 1px solid gray; \n"
"    border-radius: 5px; \n"
"}\n"
"QPushButton:hover { \n"
"    background-color: lightblue; \n"
"}\n"
"QPushButton:pressed { \n"
"    background-color: #87ceeb; \n"
"}\n"
"")
        self.pushButtonClearLogs.setObjectName("pushButtonClearLogs")
        self.verticalLayout_6.addWidget(self.pushButtonClearLogs)
        self.pushButtonStop = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonStop.setFont(font)
        self.pushButtonStop.setStyleSheet("QPushButton { \n"
"    background-color: lightgray; \n"
"    color: black; \n"
"    font-weight: bold; \n"
"    border: 1px solid gray; \n"
"    border-radius: 5px; \n"
"}\n"
"QPushButton:hover { \n"
"    background-color: red; \n"
"}\n"
"QPushButton:pressed { \n"
"    background-color: #87ceeb; \n"
"}\n"
"")
        self.pushButtonStop.setObjectName("pushButtonStop")
        self.verticalLayout_6.addWidget(self.pushButtonStop)
        self.treeWidgetJson = QtWidgets.QTreeWidget(Dialog)
        self.treeWidgetJson.setGeometry(QtCore.QRect(970, 70, 440, 711))
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [urw]")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.treeWidgetJson.setFont(font)
        self.treeWidgetJson.setStyleSheet("QTreeWidget { \n"
"    background-color: #f9f9f9; \n"
"    alternate-background-color: #e9f7fc; \n"
"    border: 1px solid gray; \n"
"}\n"
"")
        self.treeWidgetJson.setAnimated(False)
        self.treeWidgetJson.setObjectName("treeWidgetJson")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEditDomain, self.lineEditFileName)
        Dialog.setTabOrder(self.lineEditFileName, self.checkBoxSneakyAttack)
        Dialog.setTabOrder(self.checkBoxSneakyAttack, self.checkBoxModerateAttack)
        Dialog.setTabOrder(self.checkBoxModerateAttack, self.checkBoxAggressiveAttack)
        Dialog.setTabOrder(self.checkBoxAggressiveAttack, self.checkBoxShowRequests)
        Dialog.setTabOrder(self.checkBoxShowRequests, self.pushButtonScan)
        Dialog.setTabOrder(self.pushButtonScan, self.pushButtonExportJson)
        Dialog.setTabOrder(self.pushButtonExportJson, self.lineEditTimeout)
        Dialog.setTabOrder(self.lineEditTimeout, self.lineEditRequestCount)
        Dialog.setTabOrder(self.lineEditRequestCount, self.lineEditRequestLimit)
        Dialog.setTabOrder(self.lineEditRequestLimit, self.lineEditInterval)
        Dialog.setTabOrder(self.lineEditInterval, self.treeWidgetJson)
        Dialog.setTabOrder(self.treeWidgetJson, self.pushButtonStop)
        Dialog.setTabOrder(self.pushButtonStop, self.plainTextEditLogs)
        Dialog.setTabOrder(self.plainTextEditLogs, self.comboBoxFormat)
        Dialog.setTabOrder(self.comboBoxFormat, self.pushButtonClearLogs)
        Dialog.setTabOrder(self.pushButtonClearLogs, self.pushButtonSaveFormat)
        Dialog.setTabOrder(self.pushButtonSaveFormat, self.tabWidget)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Domain Subdomain scan"))
        self.labelEnterDomain.setText(_translate("Dialog", "Domain and Subdomain Scanner"))
        self.labelScanningLogs.setText(_translate("Dialog", "Scanning logs"))
        self.labelMaxReq.setText(_translate("Dialog", "Maximum requests"))
        self.labelTimeOutReq.setText(_translate("Dialog", "Time-out request"))
        self.labelIntervalReq.setText(_translate("Dialog", "Interval between requests"))
        self.labelReqCount.setText(_translate("Dialog", "Requests count"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_request), _translate("Dialog", "Request Settings"))
        self.checkBoxSneakyAttack.setText(_translate("Dialog", "Sneaky attack"))
        self.checkBoxModerateAttack.setText(_translate("Dialog", "Moderate attack"))
        self.checkBoxAggressiveAttack.setText(_translate("Dialog", "Aggressive attack"))
        self.checkBoxShowRequests.setText(_translate("Dialog", "Show requests and response"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_attack), _translate("Dialog", "Attack settings"))
        self.comboBoxFormat.setItemText(0, _translate("Dialog", "json"))
        self.comboBoxFormat.setItemText(1, _translate("Dialog", "html"))
        self.comboBoxFormat.setItemText(2, _translate("Dialog", "txt"))
        self.labelEnterFile.setText(_translate("Dialog", "   Enter file name \n"
"where save output logs. "))
        self.pushButtonSaveFormat.setText(_translate("Dialog", "Save format"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_output), _translate("Dialog", "Output Settings"))
        self.pushButtonExportJson.setText(_translate("Dialog", "Export json file"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_treeWidget), _translate("Dialog", "Json Tree Widget"))
        self.groupBox.setTitle(_translate("Dialog", "Main panel"))
        self.labelExample.setText(_translate("Dialog", "Example: fbi.com"))
        self.pushButtonScan.setText(_translate("Dialog", "Start attack!"))
        self.pushButtonClearLogs.setText(_translate("Dialog", "Clear logs"))
        self.pushButtonStop.setText(_translate("Dialog", "Stop scan"))
        self.treeWidgetJson.headerItem().setText(0, _translate("Dialog", "Subdomains"))
